version: 2.1

executors:
  pulumi:
    docker:
      - image: circleci/node:14

jobs:
  make:
    resource_class: xlarge
    executor: pulumi
    parameters:
      env:
        description: stage or prod
        type: string
    steps:
      - run: sudo apt-get install libudev-dev libusb-dev libusb-1.0
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit
      - run:
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
          command: "make && make test"
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
workflows:
  version: 2
  build-master:
    jobs:
      - make:
          name: make
          env: prod
