version: 2.1


orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

executors:
  pulumi:
    docker:
      - image: pulumi/pulumi

jobs:
  build:
    resource_class: xlarge
    executor: pulumi
    parameters:
      env:
        description: stage or prod
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command:curl -sL https://github.com/digitalocean/doctl/releases/download/v1.56.0/doctl-1.56.0-linux-amd64.tar.gz | tar -xzv
      - run:
          command:mv doctl /usr/local/bin
      - run:
          command: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run:
          name: build
          command: "doctl auth init -t $DIGITALOCEAN_TOKEN && doctl registry login && npm run build:rest"
  deploy:
    executor: pulumi
    parameters:
      env:
        description: stage or prod
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: update
          command: "cd deploy && npm i && node leeroy-sdk.js"


not_master: &not_master
  filters:
    branches:
      ignore: master

only_master: &only_master
  filters:
    branches:
      only:
        - master

only_develop: &only_develop
  filters:
    branches:
      only:
        - develop

# Blue* deployment
only_release_canidate: &only_release_canidate
  filters:
    branches:
      only:
        - release-canidate

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          <<: *only_master
          name: push image
          env: prod
      - deploy:
          <<: *only_master
          name: deploy image
          env: prod
          requires:
            - push image
